# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0002_auto_20170629_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(default='', max_length=250)),
                ('login', models.CharField(default='', max_length=250)),
                ('password', models.CharField(default='', max_length=250)),
                ('email', models.CharField(default='', max_length=250)),
                ('phone_number', models.CharField(default='', max_length=250)),
                ('street', models.CharField(default='', max_length=250)),
                ('city', models.CharField(default='', max_length=250)),
                ('country', models.CharField(default='', max_length=250)),
                ('role', models.CharField(default='', max_length=250)),
                ('salary', models.IntegerField(default='')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResource.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
