# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0003_auto_20170629_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='login',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_user',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='street',
            field=models.CharField(max_length=250),
        ),
    ]
