# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=250)),
                ('post', models.CharField(max_length=250)),
                ('trade_register', models.CharField(max_length=250)),
                ('tax_id', models.CharField(max_length=250)),
                ('RIB', models.CharField(max_length=250)),
                ('if_entreprise', models.BooleanField(default=True)),
                ('entreprise_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=250)),
                ('next_action', models.CharField(max_length=250)),
                ('priority', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('estimated_revenue', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client')),
            ],
        ),
        migrations.CreateModel(
            name='piste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piste_objective', models.CharField(max_length=250)),
                ('piste_staut', models.CharField(max_length=250)),
                ('piste_categoty', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client')),
            ],
        ),
        migrations.CreateModel(
            name='ready_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.category')),
            ],
        ),
    ]
