# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=250)),
                ('login', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=250)),
                ('post', models.CharField(max_length=250)),
                ('trade_register', models.CharField(max_length=250)),
                ('tax_id', models.CharField(max_length=250)),
                ('RIB', models.CharField(max_length=250)),
                ('if_entreprise', models.BooleanField(default=True)),
                ('entreprise_type', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='piste',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer'),
        ),
        migrations.DeleteModel(
            name='client',
        ),
    ]
